export const copy = {
  appName: 'ZigZag Planner',
  appFullName: 'ZigZag Neurodivergent Planner',
  emptyNow: 'Nothing in Now.',
  inboxClear: 'Inbox clear. Today is set.',
  whyLabel: 'Why this?',
  blockRecovery: 'Block recovery?',
  recoveryTitle: 'Recovery',
  swapPrompt: 'Next already has two. Which one moves to This week?',
  sendNewToWeek: 'Send the new one to This week',
  calendarDiffers: 'Calendar time differs.',
  keepTaskTime: 'Keep task time',
  useCalendarTime: 'Use calendar time',
  zohoSilent: "Zoho didn't answer. Your tasks are still here.",
  googleSilent: "Google didn't answer. Your tasks are still here.",
  fromDeepRoots: 'From Deep Roots',
  openInDeepRoots: 'Open in Deep Roots',
  done: 'Done',
  park: 'Park',
  swap: 'Swap',
  makeNow: 'Make this Now',
  now: 'Now',
  capturePlaceholder: 'Add something',
  enterNow: 'Enter puts this in Now.',
  enterToday: 'Enter adds this to Today.',
  enterWeek: 'Enter puts this on This week.',
  today: 'Today',
  thisWeek: 'This week',
  someday: 'Someday',
  projects: 'Projects',
  settings: 'Settings',
  inboxLeft: (n: number) => `${n} left`,
  inboxLink: (n: number) => `Inbox (${n})`,
  waiting: (n: number) => (n === 1 ? '1 waiting' : `${n} waiting`),
  sendRest: 'Send the rest to Someday',
  skip: 'Skip',
  delete: 'Delete',
  undo: 'Undo',
  connected: 'Connected',
  notConnected: 'Not connected',
  addToInbox: 'Add to inbox',
  addToToday: 'Add to today',
  addToWeek: 'Add to this week',
  putOnCalendar: 'Put on calendar',
  comingUp: 'Coming up',
  close: 'Close',
  chaplain: 'Chaplain',
  founder: 'Founder',
  personal: 'Personal',
  newProject: 'New project',
  projectName: 'Project name',
  note: 'Note',
  save: 'Save',
  back: 'Back',
  signIn: 'Sign in',
  signInMismatch: "That email and password didn't match.",
  googleClosed: "Google didn't open.",
  useThisDevice: 'Use this device only',
  sameAccount: 'Use the same email on the phone and on the computer.',
  email: 'Email',
  password: 'Password',
  createAccount: 'Create account',
  signInGoogle: 'Sign in with Google',
  connectDeepRoots: 'Connect Deep Roots',
  mcdillUid: 'Deep Roots user id',
  deepRootsHost: 'Deep Roots address',
  importSnapshot: 'Import a Deep Roots snapshot',
  homeCalendar: 'Home calendar',
  zoho: 'Zoho',
  google: 'Google',
  min15: '15 min',
  min30: '30 min',
  min60: '60 min',
  noProjects: 'No projects yet.',
  weekEmpty: 'Nothing this week.',
  somedayEmpty: 'Someday is empty.',
  due: 'Due date',
  clearDate: 'Clear date',
  captured: 'Added.',
  removeBlock: 'Remove the block',
  keepBlock: 'Keep the block',
  details: 'Details',
  signOut: 'Sign out',
  deviceNote: 'Tasks stay on this device until you sign in.',
  settingsNote: 'Connections can wait. Today already works.',
  checkoffNote: 'Check-offs saved on this device send when Deep Roots is connected.',
  calendarNote: 'Today shows what is dated today. Later dates show on This week.',
  nothingToday: 'Nothing dated today.',
  notices: 'Reminders',
  noticesNote: 'Several reminders, spread out. Turn off any you do not want.',
  noticeAt: 'When it starts',
  notice15: '15 minutes before',
  notice60: '1 hour before',
  noticeMorning: 'Morning of that day, 8:00 am',
  noticeEvening: 'Evening before, 6:00 pm',
  noticeOn: 'On',
  noticeOff: 'Off',
  syncNow: 'Sync now',
  synced: 'Synced.',
  zohoClientId: 'Zoho client id',
  zohoClientSecret: 'Zoho client secret',
  zohoRefresh: 'Zoho refresh token',
  zohoAccounts: 'Zoho accounts address',
  zohoNeedsToken: 'Add the Zoho client id, secret, and refresh token, then tap Sync now.',
  zohoBrowser: 'This browser cannot reach Zoho. Sync from the phone. The website will follow.',
  projectTasks: 'Tasks',
  noTasks: 'No tasks in this project.',
  context: 'Context',
  dismissTriage: 'Back to Today',
  length: 'Length',
  help: 'Help',
  stuck: "I'm stuck",
  crashed: 'I crashed',
  frozen: "I'm frozen",
  pickMove: 'Pick a next move.',
  keepAndRecover: 'Keep this and block recovery',
  parkAndRecover: 'Park this and block recovery',
  parkOnly: 'Park this',
  clearNow: 'Send Now to This week',
  parkAndPromote: 'Park this and start the first Next',
  startNext: 'Start the first Next',
  swapWithNext: 'Swap with Next',
  restOnly: 'Block recovery',
  sortInbox: 'Place what is waiting',
  nothingWaiting: 'Nothing is waiting.',
  helpIntro: 'Get Started is the first note. The others are the same pages, one topic each.',
} as const;

export const stuckLabels = {
  'keep-and-recover': copy.keepAndRecover,
  'park-and-recover': copy.parkAndRecover,
  park: copy.parkOnly,
  swap: copy.swapWithNext,
  'park-and-promote': copy.parkAndPromote,
  'clear-now': copy.clearNow,
  'start-next': copy.startNext,
  'recover-only': copy.restOnly,
  'open-triage': copy.sortInbox,
} as const;

const FORBIDDEN = [
  /\boverdue\b/i,
  /\bmissed\b/i,
  /\bstreaks?\b/i,
  /\bfailed\b/i,
  /\bforgot\b/i,
  /\bbehind\b/i,
  /don'?t forget/i,
  /you should/i,
  /great job/i,
  /keep it up/i,
  /\boops\b/i,
  /\bsorry\b/i,
];

export function allCopyStrings(): string[] {
  const out: string[] = [];
  for (const value of Object.values(copy)) {
    if (typeof value === 'string') out.push(value);
    else out.push(value(0), value(1), value(4), value(15));
  }
  return out;
}

export function calmCopyViolations(strings: string[]): string[] {
  const hits: string[] = [];
  for (const text of strings) {
    for (const rule of FORBIDDEN) {
      if (rule.test(text)) hits.push(text);
    }
  }
  return hits;
}
